# Generated by Django 4.2.1 on 2023-05-23 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('N', 'Natural'), ('J', 'Juridico')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('id_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Saleman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
            ],
        ),
    ]
