# Generated by Django 4.2.1 on 2023-06-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_mecanic_id_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Man', 'Manager'), ('Sel', 'Seller'), ('Mec', 'Mecanic')], max_length=5),
        ),
    ]
