# Generated by Django 4.2.1 on 2023-05-30 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_remove_customer_email_remove_customer_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.article')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('wheel', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.article')),
            ],
        ),
        migrations.CreateModel(
            name='Branch_article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.article')),
                ('id_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.branch')),
            ],
        ),
    ]
