# Generated by Django 4.2.1 on 2023-06-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_article_color_remove_article_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_article',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
