# Generated by Django 4.2.1 on 2023-06-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_branch_article_color'),
        ('inventory', '0006_car_image'),
    ]

    operations = [
    ]
