# Generated by Django 4.2.1 on 2023-06-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_article_deleted'),
        ('inventory', '0007_merge_0005_alter_branch_article_color_0006_car_image'),
    ]

    operations = [
    ]
