# Generated by Django 4.2.1 on 2023-06-26 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_car_image'),
        ('login', '0007_alter_branch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('model', models.CharField(max_length=50)),
                ('model_date', models.CharField(max_length=10)),
                ('plate', models.CharField(max_length=10)),
                ('observation', models.TextField(null=True)),
                ('amount', models.IntegerField()),
                ('id_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.customer')),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.employee')),
                ('id_replacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.replacement')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(null=True)),
                ('total', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('id_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.car')),
                ('id_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.customer')),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('TC', 'Tarjeta de crédito'), ('EF', 'Efectivo'), ('PS', 'Pse')], max_length=2)),
                ('observation', models.TextField(null=True)),
                ('total', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('id_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.car')),
                ('id_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.customer')),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.employee')),
            ],
        ),
    ]
