# Generated by Django 4.2.1 on 2023-06-26 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_car_image'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='id_car',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='id_car',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='work_order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='work_order',
            name='id_replacement',
        ),
        migrations.CreateModel(
            name='Quotation_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('id_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.car')),
                ('id_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('id_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.replacement')),
                ('id_work_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.work_order')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.bill')),
                ('id_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.car')),
            ],
        ),
    ]
