# Generated by Django 4.2.1 on 2023-06-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_car_image'),
        ('login', '0007_alter_branch_id'),
        ('order', '0002_remove_bill_amount_remove_bill_id_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='id_article',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='id_replacement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.replacement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='id_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='id_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill_detail',
            name='id_car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='id_work_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.work_order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='id_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='id_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation_detail',
            name='id_car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work_order',
            name='id_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work_order',
            name='id_employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
            preserve_default=False,
        ),
    ]
