# Generated by Django 4.2.1 on 2023-06-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_branch_id'),
        ('inventory', '0007_merge_0005_alter_branch_article_color_0006_car_image'),
        ('order', '0003_remove_order_detail_id_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.customer'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='id_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.employee'),
        ),
        migrations.AlterField(
            model_name='bill_detail',
            name='id_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.bill'),
        ),
        migrations.AlterField(
            model_name='bill_detail',
            name='id_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.car'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='id_replacement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.replacement'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='id_work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.work_order'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='id_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.customer'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='id_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.employee'),
        ),
        migrations.AlterField(
            model_name='quotation_detail',
            name='id_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.car'),
        ),
        migrations.AlterField(
            model_name='quotation_detail',
            name='id_quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.quotation'),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='id_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.customer'),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='id_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.employee'),
        ),
    ]
