# Generated by Django 4.2.1 on 2023-06-28 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_merge_0005_alter_branch_article_color_0006_car_image'),
        ('order', '0004_alter_bill_id_customer_alter_bill_id_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_detail',
            name='id_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.branch_article'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='id_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.branch_article'),
        ),
    ]
