# Generated by Django 4.2.1 on 2023-06-28 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_detail_id_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_detail',
            name='id_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.bill'),
        ),
        migrations.AlterField(
            model_name='quotation_detail',
            name='id_quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.quotation'),
        ),
    ]
